version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false

  app:
    build: .
    container_name: ecommerce-app
    volumes:
      - .:/app
    depends_on:
      - elasticsearch
    tty: true
